<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="15" passed="15">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="1145" started-at="2016-10-26T21:41:36Z" finished-at="2016-10-26T21:41:37Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="1145" started-at="2016-10-26T21:41:36Z" finished-at="2016-10-26T21:41:37Z">
      <class name="by.epam.lab.testing.test.unit.GoTestingUnitTest">
        <test-method status="PASS" signature="negativTest(java.lang.String, java.util.List)[pri:0, instance:by.epam.lab.testing.test.unit.GoTestingUnitTest@57bc27f5]" name="negativTest" duration-ms="8" started-at="2016-10-27T00:41:37Z" data-provider="goTestingNegativeTest" finished-at="2016-10-27T00:41:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[5]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativTest -->
        <test-method status="PASS" signature="positiveTest(java.lang.String, java.util.List)[pri:0, instance:by.epam.lab.testing.test.unit.GoTestingUnitTest@57bc27f5]" name="positiveTest" duration-ms="6" started-at="2016-10-27T00:41:37Z" data-provider="goTestingPositiveTest" finished-at="2016-10-27T00:41:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[MATH]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[3]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- positiveTest -->
      </class> <!-- by.epam.lab.testing.test.unit.GoTestingUnitTest -->
      <class name="by.epam.lab.testing.test.unit.ShowSubjectListTest">
        <test-method status="PASS" signature="positiveTest(java.lang.String)[pri:0, instance:by.epam.lab.testing.test.unit.ShowSubjectListTest@790da477]" name="positiveTest" duration-ms="21" started-at="2016-10-27T00:41:37Z" data-provider="showSubjectPositiveTest" finished-at="2016-10-27T00:41:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[SHOW_SUBJECT]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- positiveTest -->
        <test-method status="PASS" signature="secondPositiveTest(java.util.List)[pri:0, instance:by.epam.lab.testing.test.unit.ShowSubjectListTest@790da477]" name="secondPositiveTest" duration-ms="3" started-at="2016-10-27T00:41:37Z" data-provider="showSubjectPositiveTestSecond" finished-at="2016-10-27T00:41:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[MATH]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- secondPositiveTest -->
      </class> <!-- by.epam.lab.testing.test.unit.ShowSubjectListTest -->
      <class name="by.epam.lab.testing.test.unit.ShowQuestionListTest">
        <test-method status="PASS" signature="negativeTest()[pri:0, instance:by.epam.lab.testing.test.unit.ShowQuestionListTest@5c7933ad]" name="negativeTest" duration-ms="4" started-at="2016-10-27T00:41:37Z" finished-at="2016-10-27T00:41:37Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at by.epam.lab.testing.controller.Controller.doRequest(Controller.java:23)
	at by.epam.lab.testing.test.unit.ShowQuestionListTest.negativeTest(ShowQuestionListTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeTest -->
        <test-method status="PASS" signature="positiveTest(java.lang.String, java.lang.String)[pri:0, instance:by.epam.lab.testing.test.unit.ShowQuestionListTest@5c7933ad]" name="positiveTest" duration-ms="7" started-at="2016-10-27T00:41:37Z" data-provider="showQuestionPositiveTest" finished-at="2016-10-27T00:41:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[MATH]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[SHOW_QUESTION]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- positiveTest -->
        <test-method status="PASS" signature="positiveTestSecond(java.lang.String, java.util.List)[pri:0, instance:by.epam.lab.testing.test.unit.ShowQuestionListTest@5c7933ad]" name="positiveTestSecond" duration-ms="7" started-at="2016-10-27T00:41:37Z" data-provider="showQuestionPositiveTestSecond" finished-at="2016-10-27T00:41:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[MATH]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[Решите уравнение: x=2x-150
		1. x = 50
		2. x = -150
		3. x = 150
		4. x = -50]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- positiveTestSecond -->
      </class> <!-- by.epam.lab.testing.test.unit.ShowQuestionListTest -->
      <class name="by.epam.lab.testing.test.unit.AuthirizationTest">
        <test-method status="PASS" signature="negativTestOne(java.lang.String, java.lang.String)[pri:0, instance:by.epam.lab.testing.test.unit.AuthirizationTest@431cd9b2]" name="negativTestOne" duration-ms="13" started-at="2016-10-27T00:41:37Z" data-provider="authorizationNegativeTest" finished-at="2016-10-27T00:41:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Unknown]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[qwerty]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativTestOne -->
        <test-method status="PASS" signature="negativTestTwo()[pri:0, instance:by.epam.lab.testing.test.unit.AuthirizationTest@431cd9b2]" name="negativTestTwo" duration-ms="3" started-at="2016-10-27T00:41:37Z" finished-at="2016-10-27T00:41:37Z">
          <exception class="by.epam.lab.testing.dao.exception.DAOException">
            <message>
              <![CDATA[It's can't be empty data]]>
            </message>
            <full-stacktrace>
              <![CDATA[by.epam.lab.testing.dao.exception.DAOException: It's can't be empty data
	at by.epam.lab.testing.dao.impl.UserDAOImpl.authorization(UserDAOImpl.java:21)
	at by.epam.lab.testing.test.unit.AuthirizationTest.negativTestTwo(AuthirizationTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- by.epam.lab.testing.dao.exception.DAOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativTestTwo -->
        <test-method status="PASS" signature="positiveTest(java.lang.String, java.lang.String)[pri:0, instance:by.epam.lab.testing.test.unit.AuthirizationTest@431cd9b2]" name="positiveTest" duration-ms="11" started-at="2016-10-27T00:41:37Z" data-provider="authorizationPositiveTest" finished-at="2016-10-27T00:41:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[NewUser]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[qwerty]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- positiveTest -->
      </class> <!-- by.epam.lab.testing.test.unit.AuthirizationTest -->
      <class name="by.epam.lab.testing.test.unit.RegistrationTest">
        <test-method status="PASS" signature="positiveTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:by.epam.lab.testing.test.unit.RegistrationTest@26abb146]" name="positiveTest" duration-ms="632" started-at="2016-10-27T00:41:36Z" data-provider="registrationPositiveTest" finished-at="2016-10-27T00:41:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[NewUser]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[qwerty]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[REGISTRATION]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- positiveTest -->
      </class> <!-- by.epam.lab.testing.test.unit.RegistrationTest -->
      <class name="by.epam.lab.testing.test.unit.SetNewSubjectTest">
        <test-method status="PASS" signature="negativeTestOne()[pri:0, instance:by.epam.lab.testing.test.unit.SetNewSubjectTest@38467116]" name="negativeTestOne" duration-ms="5" started-at="2016-10-27T00:41:37Z" finished-at="2016-10-27T00:41:37Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at by.epam.lab.testing.controller.Controller.doRequest(Controller.java:23)
	at by.epam.lab.testing.test.unit.SetNewSubjectTest.negativeTestOne(SetNewSubjectTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeTestOne -->
        <test-method status="PASS" signature="positiveTest(java.lang.String, java.lang.String)[pri:0, instance:by.epam.lab.testing.test.unit.SetNewSubjectTest@38467116]" name="positiveTest" duration-ms="21" started-at="2016-10-27T00:41:37Z" data-provider="setNewSubjectPositiveTest" finished-at="2016-10-27T00:41:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[MATH]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[CREATE_NEW_SUBJECT]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- positiveTest -->
      </class> <!-- by.epam.lab.testing.test.unit.SetNewSubjectTest -->
      <class name="by.epam.lab.testing.test.unit.SetNewQuestionTest">
        <test-method status="PASS" signature="negativeTestOne()[pri:0, instance:by.epam.lab.testing.test.unit.SetNewQuestionTest@5b7a7f33]" name="negativeTestOne" duration-ms="12" started-at="2016-10-27T00:41:37Z" finished-at="2016-10-27T00:41:37Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at by.epam.lab.testing.controller.Controller.doRequest(Controller.java:23)
	at by.epam.lab.testing.test.unit.SetNewQuestionTest.negativeTestOne(SetNewQuestionTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeTestOne -->
        <test-method status="PASS" signature="positivTest(java.lang.String, java.lang.String, int, java.lang.String)[pri:0, instance:by.epam.lab.testing.test.unit.SetNewQuestionTest@5b7a7f33]" name="positivTest" duration-ms="21" started-at="2016-10-27T00:41:37Z" data-provider="setNewQuestionPositiveTest" finished-at="2016-10-27T00:41:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[MATH]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Решите уравнение: x=2x-150
		1. x = 50
		2. x = -150
		3. x = 150
		4. x = -50]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[CREATE_NEW_QUESTION]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- positivTest -->
      </class> <!-- by.epam.lab.testing.test.unit.SetNewQuestionTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
